events{
    worker_connections 1024;
}

http{
    include /etc/nginx/mime.types;

    limit_req_zone $binary_remote_addr zone=req_lim:10m rate=10r/s;

    server{
        listen 80;
        return https://$host$request_uri;
    }
    server{
        listen 443 ssl;

        ssl_certificate /etc/nginx/certs/fullchain.pem;
        ssl_certificate_key /etc/nginx/certs/privkey.pem;

        location /static/{
            alias /usr/share/nginx/static/;
        }
        location /{
            limit_req zone=req_lim burst=20 nodelay;

            client_max_body_size 10M;

            proxy_pass http://site:1080;
            proxy_set_header Host $host;
            proxy_set_header X-Real-Ip $remote_addr;
        }
    }
}


